disabled_rules:
  - trailing_comma
  - nesting
  - large_tuple
  - blanket_disable_command

identifier_name:
  min_length: 2
  excluded:
    - hd
    - sd
    - id
  allowed_symbols: ["_"]

excluded:
  - .build
