name: build-documentation
on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build-docc:
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Xcodebuild DocC Action
        uses: lukepistrol/xcodebuild-docc-action@0.0.1
        with:
          scheme: PexelsSwift
          platform: macos
          output-path: ./docs
          clean: true
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs
          git init
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
        
      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: docs
          force: true
          directory: ./docs
