name: tests
on:
  push:
    branches:
      - 'test'
  pull-request:
    branches:
      - 'test'
jobs:
  pexels-swift-tests:
    name: Testing Pexels-Swift
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing Package
        run: exec ./.github/scripts/test.sh arm ${{ secrets.PEXELS_API_KEY }}