name: tests
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
jobs:
  pexels-swift-tests:
    name: Testing Pexels-Swift
    runs-on: macos-12
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Testing Package
        run: exec ./.github/scripts/tests.sh ${{ secrets.PEXELS_API_KEY }}